# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44afac70d17e0b2afb5c31c28938039400116aa313a2513b8e4e2d6667b61720109ace3b17858c27edbb43a9cd6cc155e3047414491af52b876086468fbba5de

test:
  secret_key_base: 517e5593f6dbcbd227a0579e31981bb03cf354405c160677b7ca1e9137c392e0fba08cba89565347e566a8b1a303de2b1ddb0ac79cd9005f99a1fcafc6f12e92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
